START TRANSACTION;

CREATE TABLE IF NOT EXISTS users
(
    id       INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    login    VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255)        NOT NULL
);

COMMIT